config/routes.rb
Rails.application.routes.draw do
  resources :businesses

  get 'admin', to: 'admin#index'

  resources :profiles

  get 'home/index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :manage, Profile, :user_id => user.id
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  mount_uploader :picture, ProfilePictureUploader

  def full_name
  	[first_name, last_name].join(' ')
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_one :profile			
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :add_profile_for_new_user

  def add_profile_for_new_user
  	self.profile = Profile.new
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :tagline, :decription, :url, :owner_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :show
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :picture, :city, :country, :phone, :dob, :tagline, :info, :website, :twitter, :facebook, :linkedin, :google_plus, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_profile_path(resource.profile)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/businesses/_form.html.erb
<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :tagline, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :decription, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :url, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :owner_id, input_html: { class: 'form-control'} %>
  	</div>		


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tagline</th>
      <th>Decription</th>
      <th>Url</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.tagline %></td>
        <td><%= business.decription %></td>
        <td><%= business.url %></td>
        <td><%= business.owner_id %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @business.tagline %>
</p>

<p>
  <strong>Decription:</strong>
  <%= @business.decription %>
</p>

<p>
  <strong>Url:</strong>
  <%= @business.url %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @business.owner_id %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/home/index.html.erb
<h1>Welcome to the Startup Community</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to 'GET STARTED', new_user_registration_path, class: 'btn btn-success btn-lg' %>
 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Startup Community</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <li><%= link_to 'Admin', admin_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.profile.first_name %> <%= current_user.profile.last_name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="<%= profile_path(current_user.profile) %>">My Account</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Already a member?', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Startup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style='padding-top:50px;'>
<%= render 'layouts/navbar' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    <%= f.input :first_name, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :last_name, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :picture, as: :file, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :city, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :country, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :phone, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :dob, start_year: Date.today.year - 110, end_year: Date.today.year - 5, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :tagline, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :info, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :website, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :twitter, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :facebook, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :linkedin, input_html: { class: 'form-control'} %>
  	</div>		
  	<div class="form-group">
    <%= f.input :google_plus, input_html: { class: 'form-control'} %>
  	</div>				


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Picture</th>
      <th>City</th>
      <th>Country</th>
      <th>Phone</th>
      <th>Dob</th>
      <th>Tagline</th>
      <th>Info</th>
      <th>Website</th>
      <th>Twitter</th>
      <th>Facebook</th>
      <th>Linkedin</th>
      <th>Google plus</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.picture %></td>
        <td><%= profile.city %></td>
        <td><%= profile.country %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.dob %></td>
        <td><%= profile.tagline %></td>
        <td><%= profile.info %></td>
        <td><%= profile.website %></td>
        <td><%= profile.twitter %></td>
        <td><%= profile.facebook %></td>
        <td><%= profile.linkedin %></td>
        <td><%= profile.google_plus %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@profile.picture_url(:thumbnail)) %>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile.country %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile.phone %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @profile.dob %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @profile.tagline %>
</p>

<p>
  <strong>Info:</strong>
  <%= @profile.info %>
</p>

<p>
  <strong>Website:</strong>
  <%= @profile.website %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @profile.twitter %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @profile.facebook %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @profile.linkedin %>
</p>

<p>
  <strong>Google plus:</strong>
  <%= @profile.google_plus %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

<% if user_signed_in? %>
  <% if current_user == @profile.user %>
    <%= link_to 'Edit', edit_profile_path(@profile), class: 'btn btn-warning' %>
  <% end %>
<% end %>